### ISSUE TITLE
Stable docs not built automatically

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#47]
The "stable" docs don't seem to be built automatically. Only the "latest" reflect the current master.

@mixxorz Can you take a look at the configuration on RTD? https://readthedocs.org/projects/behave-django/

Is that configured to be manually triggered, maybe? The stable should be built when we push a tag.

**Comment by mixxorz** [comment]
It should be but rtd isn't doing it. I'm not sure how to make it do that tbh. :/

**Comment by bittner** [comment]
What we could do is make the docs build from Travis when a tag is pushed, e.g.
```yaml
notifications:
  webhooks:
    urls:
      - https://readthedocs.org/build/behave-django
```
... but I can't see from the [Travis docs](https://docs.travis-ci.com/user/notifications/) how to make this work only with tags.

Alternatively, add a webhook to the GitHub settings [as described in the RTD docs](docs.readthedocs.io/en/latest/webhooks.html#github). I think that offers all the control we need (i.e. tags).

Maybe it would also make sense to set the default docs to "latest" instead of "stable".

**Comment by bittner** [comment]
@mixxorz Did you have time to try whether [adding a webhook](http://docs.readthedocs.io/en/latest/webhooks.html#github) to the GitHub settings resolves the situation for us? (I don't have the permissions to access the repository settings.)

**Comment by mixxorz** [comment]
It's working now. I found a Sphinx warning when I rebuilt the docs locally. I fixed the warning. That might be why rtd didn't automatically build the docs before.

<img width="820" alt="screenshot 2018-01-29 20 31 49" src="https://user-images.githubusercontent.com/3102758/35510586-a08e8c0e-0533-11e8-8822-6b172aa1defb.png">

**Comment by bittner** [comment]
Awesome, thanks! :+1:

**Comment by bittner** [comment]
This is still an issue. Only the "latest" docs are up-to-date.

@mixxorz Can you check the settings again? (I have no access to neither the [project settings](https://github.com/behave/behave-django/settings) on GitHub nor the [behave-django project](https://readthedocs.org/projects/behave-django/) on ReadTheDocs.org)

**Comment by mixxorz** [comment]
Ah it seems changes in GitHub has affected RTD. I've gone ahead and configured a new webhook for RTD. This working properly now.

**Comment by bittner** [comment]
Would you care (or worry) to run the same multi-maintainer policy with RTD and the GitHub project as with PyPI? I think that would be good. Reduces the bus factor.

**Comment by mixxorz** [comment]
I've added both you (uname: bittner) and jenisys (uname: jenisys)

**Comment by bittner** [comment]
That looks good, thank you! :1st_place_medal:
